angular.module("route",['ngRoute'])
    .config(["$routeProvider",function ($routeProvider) {
        $routeProvider.when("/myAc",{
            templateUrl:"../tpl/addOffer.html",
            controller:"myAc"
        }).when("/",{
            templateUrl:"../tpl/dashboard.html",
            controller:"dashboard"
        }).when("/affApply",{
            templateUrl:"../tpl/affApply.html",
            controller:"affApply"
        }).when("/apps/:type",{
            templateUrl:"../tpl/apps.html",
            controller:"apps"
        }).when("/appDetail/:id/:table",{
            templateUrl:"../tpl/appDetail.html",
            controller:"appDetail"
        }).when('/addCart/:id/:flag',{
            templateUrl:'../tpl/addCart.html',
            controller:"addCart"
        }).when("/addTrace/:id",{
            templateUrl:'../tpl/addTrace.html',
            controller:"addTrace"
        }).when("/offers/:type",{
            templateUrl:"../tpl/offers.html",
            controller:"offers"
        }).when("/offersDetail/:id",{
            templateUrl:"../tpl/offersDetail.html",
            controller:"offersDetail"
        }).when("/editOffers/:id",{
            templateUrl:"../tpl/editOffers.html",
            controller:"editOffers"
        }).when("/advFilter",{
            templateUrl:"../tpl/advFilter.html",
            controller:"advFilter"
        }).when("/affFilter",{
            templateUrl:"../tpl/affFilter.html",
            controller:"affFilter"
        }).when("/offerReport",{
            templateUrl:"../tpl/offerReport.html",
            controller:"offerReport"
        }).when("/appReport",{
            templateUrl:"../tpl/appReport.html",
            controller:"appReport"
        }).when("/qualityReport",{
            templateUrl:"../tpl/qualityReport.html",
            controller:"qualityReport"
        }).when("/qualityReportDetail/:net/:offer/:app/:aff/:start/:end/:type",{
            templateUrl:"../tpl/qualityReportDetail.html",
            controller:"qualityReportDetail"
        }).when("/billReport",{
            templateUrl:"../tpl/billReport.html",
            controller:"billReport"
        }).when("/view/:para/:month/:confirm",{
            templateUrl:"../tpl/view.html",
            controller:"view"
        }).when("/billingDetail/:para/:month",{
            templateUrl:"../tpl/billingDetail.html",
            controller:"billingDetail"
        }).when("/billAffReport",{
            templateUrl:"../tpl/billAffReport.html",
            controller:"billAffReport"
        }).when("/billAffReportDetail/:month/:affId",{
            templateUrl:"../tpl/billAffReportDetail.html",
            controller:"billAffReportDetail"
        }).when("/holdBilling",{
            templateUrl:"../tpl/holdBilling.html",
            controller:"holdBilling"
        }).when("/addOffer",{
            templateUrl:"../tpl/myAcount.html",
            controller:"addOffer"
        }).when("/seeDetail/:system/:id/:accept/:packageName/:name/:netId",{
            templateUrl:'../tpl/seeDetail.html',
            controller:"seeDetail"
        }).when("/advAccount",{
            templateUrl:'../tpl/advAccount.html',
            controller:"advAccount"
        }).when("/advAccountDetail/:id/:info",{
            templateUrl:'../tpl/advAccountDetail.html',
            controller:"advAccountDetail"
        }).when("/advAccountPre/:id",{
            templateUrl:'../tpl/advAccountPre.html',
            controller:"advAccountPre"
        }).when("/affAccount",{
            templateUrl:"../tpl/affAccount.html",
            controller:"affAccount"
        }).when("/affAccountDetail/:id/:info/:type",{
            templateUrl:'../tpl/affAccountDetail.html',
            controller:"affAccountDetail"
        }).when("/trafficInfo/:id/:info/:type",{
            templateUrl:'../tpl/trafficInfo.html',
            controller:"trafficInfo"
        }).when("/payInfo/:id/:info/:type",{
            templateUrl:'../tpl/payInfo.html',
            controller:"payInfo"
        }).when("/password/:id/:info/:type",{
            templateUrl:'../tpl/password.html',
            controller:"password"
        })
    }])